FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm i -g @nestjs/cli
RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine as production

COPY --from=build /app/package*.json ./
RUN npm ci --production
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/.env.example ./.env

CMD ["npm", "run", "start:with-prisma-migrate"]