name: home-library-dev
services:
  postgres-service:
    container_name: ${DB_CONTAINER_DEV}
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - library-net
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend-service:
    container_name: ${BACK_CONTAINER_DEV}
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "cd /app/ && npm install && npm run start:dev"
    environment:
      - HOST=${BACK_CONTAINER_DEV}
      - PORT=${PORT}
      - POSTGRES_HOST=${DB_CONTAINER_DEV}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - library-net
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres-service
networks:
  library-net: {}
volumes:
  postgres-data: {}